#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP=XFCE
export XDG_SESSION_TYPE=x11
export DISPLAY=:0

dbus-launch --exit-with-session startxfce4 &

sleep 3

xset -dpms s off s noblank 2>/dev/null || true
xsetroot -solid grey 2>/dev/null || true

exit 0
