#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export HOME=/home/agent
export XKL_XMODMAP_DISABLE=1
export XDG_CURRENT_DESKTOP=XFCE
export XDG_SESSION_TYPE=x11
export XDG_RUNTIME_DIR=/run/user/1000
export DISPLAY=:0

mkdir -p /run/user/1000
chown agent:agent /run/user/1000

eval $(dbus-launch --sh-syntax)
export DBUS_SESSION_BUS_ADDRESS

exec /usr/bin/xfce4-session
